import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/theme.css";
import { EB_Garamond } from "next/font/google";

export const metadata = {
  title: "Physio Therapy",
  description: "Generated by create next app",
};
const garamond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-garamond",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={garamond.className} suppressHydrationWarning>
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
